name: firebase_hosting_api_client
description: A Dart client for the Firebase Hosting API.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  googleapis_auth: ^1.2.0
